version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: safety
      MYSQL_PASSWORD: safetypassword
      MYSQL_DATABASE: safety

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: workspacify2023
      MYSQL_USER: safety
      MYSQL_PASSWORD: safetypassword
      MYSQL_DATABASE: safety
